### ISSUE TITLE
Add the default en messages?

### ISSUE THREAD

**Issue by stephan-v** [nik-m2/js-laravel-validation#3]
Is there a specific reason the default EN messages are not implemented like they are in Laravel by default?

I am talking about this file:

https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php

If the same messages were implemented in `message.js` you wouldn't need to load them from Laravel or manually specify them yourself.

**Comment by nik-m2** [comment]
Hi, I haven't seen this! I didn't realize that there were default messages in Laravel, I will implement them

**Comment by stephan-v** [comment]
The rule attribute replacements is being done with this trait: 

https://github.com/illuminate/validation/blob/9b2ef76ebb81bffad941514f0b95754434229023/Concerns/ReplacesAttributes.php

The attribute placeholder replacement is being done here:

https://github.com/illuminate/validation/blob/9b2ef76ebb81bffad941514f0b95754434229023/Concerns/FormatsMessages.php#L277

What is comes down to is that the field name(input name) is being used for the replacement.

The closest thing you can find for documentation is this:

https://laravel.com/docs/5.8/validation

Otherwise you have to resort to the source documentation. Unfortunately I don't really have the time to help out on the PR. Hope this helps though.

**Comment by nik-m2** [comment]
@stephan-v Yes those file links help a lot thank you. I should have the PR merged and published to npm today. I'll also see if I can add messages in different languages in the release
